namespace testAppDesign {
    partial class controlUserMenu {
        /// <summary> 
        /// Required constructor variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Free up all used resources.
        /// </summary>
        /// <param name="disposing">true if the managed resource should be deleted; otherwise, it is false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code automatically generated by the component designer

        /// <summary> 
        /// Required method for constructor support - do not modify
        /// the contents of this method using a code editor.
        /// </summary>
        private void InitializeComponent() {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(controlUserMenu));
            this.btnShowAll = new Bunifu.Framework.UI.BunifuFlatButton();
            this.btnSearch = new Bunifu.Framework.UI.BunifuFlatButton();
            this.activeBar = new System.Windows.Forms.Panel();
            this.btnBasket = new Bunifu.Framework.UI.BunifuFlatButton();
            this.pictureUser = new System.Windows.Forms.PictureBox();
            this.textUserMenu = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.pictureUser)).BeginInit();
            this.SuspendLayout();
            // 
            // btnShowAll
            // 
            this.btnShowAll.Activecolor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(60)))), ((int)(((byte)(73)))));
            this.btnShowAll.BackColor = System.Drawing.Color.Transparent;
            this.btnShowAll.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnShowAll.BorderRadius = 0;
            this.btnShowAll.ButtonText = "Show All Animals";
            this.btnShowAll.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnShowAll.DisabledColor = System.Drawing.Color.Gray;
            this.btnShowAll.Font = new System.Drawing.Font("Comic Sans MS", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.btnShowAll.ForeColor = System.Drawing.Color.White;
            this.btnShowAll.Iconcolor = System.Drawing.Color.Transparent;
            this.btnShowAll.Iconimage = ((System.Drawing.Image)(resources.GetObject("btnShowAll.Iconimage")));
            this.btnShowAll.Iconimage_right = null;
            this.btnShowAll.Iconimage_right_Selected = null;
            this.btnShowAll.Iconimage_Selected = null;
            this.btnShowAll.IconMarginLeft = 0;
            this.btnShowAll.IconMarginRight = 0;
            this.btnShowAll.IconRightVisible = true;
            this.btnShowAll.IconRightZoom = 0D;
            this.btnShowAll.IconVisible = true;
            this.btnShowAll.IconZoom = 40D;
            this.btnShowAll.IsTab = false;
            this.btnShowAll.Location = new System.Drawing.Point(7, 239);
            this.btnShowAll.Margin = new System.Windows.Forms.Padding(7, 7, 7, 7);
            this.btnShowAll.Name = "btnShowAll";
            this.btnShowAll.Normalcolor = System.Drawing.Color.Transparent;
            this.btnShowAll.OnHovercolor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(60)))), ((int)(((byte)(73)))));
            this.btnShowAll.OnHoverTextColor = System.Drawing.Color.White;
            this.btnShowAll.selected = false;
            this.btnShowAll.Size = new System.Drawing.Size(257, 53);
            this.btnShowAll.TabIndex = 12;
            this.btnShowAll.Text = "Show All Animals";
            this.btnShowAll.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnShowAll.Textcolor = System.Drawing.Color.White;
            this.btnShowAll.TextFont = new System.Drawing.Font("Comic Sans MS", 15.75F);
            this.btnShowAll.Click += new System.EventHandler(this.btnShowAll_Click);
            // 
            // btnSearch
            // 
            this.btnSearch.Activecolor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(60)))), ((int)(((byte)(73)))));
            this.btnSearch.BackColor = System.Drawing.Color.Transparent;
            this.btnSearch.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnSearch.BorderRadius = 0;
            this.btnSearch.ButtonText = "Search Animal";
            this.btnSearch.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnSearch.DisabledColor = System.Drawing.Color.Gray;
            this.btnSearch.Font = new System.Drawing.Font("Comic Sans MS", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.btnSearch.ForeColor = System.Drawing.Color.White;
            this.btnSearch.Iconcolor = System.Drawing.Color.Transparent;
            this.btnSearch.Iconimage = ((System.Drawing.Image)(resources.GetObject("btnSearch.Iconimage")));
            this.btnSearch.Iconimage_right = null;
            this.btnSearch.Iconimage_right_Selected = null;
            this.btnSearch.Iconimage_Selected = null;
            this.btnSearch.IconMarginLeft = 0;
            this.btnSearch.IconMarginRight = 0;
            this.btnSearch.IconRightVisible = true;
            this.btnSearch.IconRightZoom = 0D;
            this.btnSearch.IconVisible = true;
            this.btnSearch.IconZoom = 40D;
            this.btnSearch.IsTab = false;
            this.btnSearch.Location = new System.Drawing.Point(7, 185);
            this.btnSearch.Margin = new System.Windows.Forms.Padding(7, 7, 7, 7);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.Normalcolor = System.Drawing.Color.Transparent;
            this.btnSearch.OnHovercolor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(60)))), ((int)(((byte)(73)))));
            this.btnSearch.OnHoverTextColor = System.Drawing.Color.White;
            this.btnSearch.selected = false;
            this.btnSearch.Size = new System.Drawing.Size(257, 53);
            this.btnSearch.TabIndex = 11;
            this.btnSearch.Tag = "";
            this.btnSearch.Text = "Search Animal";
            this.btnSearch.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSearch.Textcolor = System.Drawing.Color.White;
            this.btnSearch.TextFont = new System.Drawing.Font("Comic Sans MS", 15.75F);
            this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
            // 
            // activeBar
            // 
            this.activeBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(79)))), ((int)(((byte)(58)))));
            this.activeBar.Location = new System.Drawing.Point(0, 185);
            this.activeBar.Name = "activeBar";
            this.activeBar.Size = new System.Drawing.Size(7, 52);
            this.activeBar.TabIndex = 10;
            // 
            // btnBasket
            // 
            this.btnBasket.Activecolor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(60)))), ((int)(((byte)(73)))));
            this.btnBasket.BackColor = System.Drawing.Color.Transparent;
            this.btnBasket.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnBasket.BorderRadius = 0;
            this.btnBasket.ButtonText = "Basket";
            this.btnBasket.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnBasket.DisabledColor = System.Drawing.Color.Gray;
            this.btnBasket.Font = new System.Drawing.Font("Comic Sans MS", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.btnBasket.ForeColor = System.Drawing.Color.White;
            this.btnBasket.Iconcolor = System.Drawing.Color.Transparent;
            this.btnBasket.Iconimage = ((System.Drawing.Image)(resources.GetObject("btnBasket.Iconimage")));
            this.btnBasket.Iconimage_right = null;
            this.btnBasket.Iconimage_right_Selected = null;
            this.btnBasket.Iconimage_Selected = null;
            this.btnBasket.IconMarginLeft = 0;
            this.btnBasket.IconMarginRight = 0;
            this.btnBasket.IconRightVisible = true;
            this.btnBasket.IconRightZoom = 0D;
            this.btnBasket.IconVisible = true;
            this.btnBasket.IconZoom = 40D;
            this.btnBasket.IsTab = false;
            this.btnBasket.Location = new System.Drawing.Point(7, 293);
            this.btnBasket.Margin = new System.Windows.Forms.Padding(7, 7, 7, 7);
            this.btnBasket.Name = "btnBasket";
            this.btnBasket.Normalcolor = System.Drawing.Color.Transparent;
            this.btnBasket.OnHovercolor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(60)))), ((int)(((byte)(73)))));
            this.btnBasket.OnHoverTextColor = System.Drawing.Color.White;
            this.btnBasket.selected = false;
            this.btnBasket.Size = new System.Drawing.Size(257, 53);
            this.btnBasket.TabIndex = 13;
            this.btnBasket.Text = "Basket";
            this.btnBasket.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBasket.Textcolor = System.Drawing.Color.White;
            this.btnBasket.TextFont = new System.Drawing.Font("Comic Sans MS", 15.75F);
            this.btnBasket.Click += new System.EventHandler(this.btnBasket_Click);
            // 
            // pictureUser
            // 
            this.pictureUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pictureUser.BackgroundImage")));
            this.pictureUser.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.pictureUser.InitialImage = ((System.Drawing.Image)(resources.GetObject("pictureUser.InitialImage")));
            this.pictureUser.Location = new System.Drawing.Point(7, 3);
            this.pictureUser.Name = "pictureUser";
            this.pictureUser.Size = new System.Drawing.Size(240, 108);
            this.pictureUser.TabIndex = 19;
            this.pictureUser.TabStop = false;
            this.pictureUser.WaitOnLoad = true;
            // 
            // textUserMenu
            // 
            this.textUserMenu.AutoSize = true;
            this.textUserMenu.BackColor = System.Drawing.Color.Transparent;
            this.textUserMenu.Font = new System.Drawing.Font("Comic Sans MS", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.textUserMenu.ForeColor = System.Drawing.Color.White;
            this.textUserMenu.Location = new System.Drawing.Point(78, 114);
            this.textUserMenu.Name = "textUserMenu";
            this.textUserMenu.Size = new System.Drawing.Size(117, 29);
            this.textUserMenu.TabIndex = 20;
            this.textUserMenu.Text = "User Menu";
            // 
            // controlUserMenu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(70)))), ((int)(((byte)(83)))));
            this.Controls.Add(this.textUserMenu);
            this.Controls.Add(this.pictureUser);
            this.Controls.Add(this.btnBasket);
            this.Controls.Add(this.btnShowAll);
            this.Controls.Add(this.btnSearch);
            this.Controls.Add(this.activeBar);
            this.Name = "controlUserMenu";
            this.Size = new System.Drawing.Size(264, 648);
            ((System.ComponentModel.ISupportInitialize)(this.pictureUser)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuFlatButton btnShowAll;
        private Bunifu.Framework.UI.BunifuFlatButton btnSearch;
        private System.Windows.Forms.Panel activeBar;
        private Bunifu.Framework.UI.BunifuFlatButton btnBasket;
        private System.Windows.Forms.PictureBox pictureUser;
        private System.Windows.Forms.Label textUserMenu;
    }
}
